### ISSUE TITLE
Thanks for scrampy

### ISSUE THREAD

**Issue by tlocke** [cagdass/scrampy#1]
Hi, I'm a maintainer of [pg8000](https://github.com/tlocke/pg8000) and reading through scrampy was a great help in writing the SCRAM authentication code. So just wanted to thank you and give you credit :-)

https://github.com/tlocke/pg8000/commit/2dd470f894b2f48b800d98ebee3aa5d4a88e92ab

I'm considering moving the SCRAM code out of pg8000 and making it a separate project, but at the same time I don't want to duplicate your efforts. Anyway, let me know if you have any thoughts on this.

Cheers,

Tony.

**Comment by cagdass** [comment]
Hey, welcome :-) Do as you will and let me know if I can help with anything

/Çağdaş
